[package]
name = "CetusAggregatorSimple"
version = "0.1.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0x1979b3234dce8e545947a3f85ded8e4dbc982bd7d1806e8dbc3a01cb8a568bbe"

[dependencies]
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "sui-v1.2.0", override = true }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "mainnet-v1.49.0", override = true }
FlowxClmm = { local = "../../externals/flowx-clmm", override = true }
TurbosDex = { local = "../../externals/turbos-dex", override = true }
BluefinSpot = { git = "https://github.com/fireflyprotocol/bluefin-spot-contract-interface.git", subdir = "", rev = "main", override = true }
Pyth = { git = "https://github.com/pyth-network/pyth-crosschain.git", subdir = "target_chains/sui/contracts", rev = "sui-contract-mainnet", override = true }
haedal_pmm = { local = "../../externals/haedal-pmm", override = true }
mmt_v3 = { local = "../../externals/mmt_v3", override = true }
obric = { local = "../../externals/obric", override = true }
Deepbookv3VaultsV2 = { local = "../../internals/deepbookv3-vaults-v2", override = true }
deepbookv3 = { local = "../../externals/deepbookv3/deepbook", override = true}

[addresses]
cetus_aggregator_simple = "0x3239061b389dcc35be021bb13d174da82fafcc87bf3d8e176e6c62619311a90c"
