[package]
name = "CetusAggregatorSimple"
version = "0.1.1"
edition = "2024.beta" # edition = "legacy" to use legacy (pre-2024) Move
published-at = "0xd65f4fb608cd629d081e9de857d1dabc90cbdddcd4db56dd296b1dd1ab6b8555"

[dependencies]
# Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "mainnet-v1.48.2", override = true }
# SuiSystem = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-system", rev = "mainnet-v1.48.2", override = true }
IntegerMate = { git = "https://github.com/CetusProtocol/integer-mate.git", subdir = "sui", rev = "sui-v1.1.2", override = true  }
CetusClmm = { git = "https://github.com/CetusProtocol/cetus-clmm-interface.git", subdir = "sui/cetus_clmm", rev = "mainnet-v1.48.3", override = true }
FlowxClmm = { local = "../externals/flowx-clmm", override = true }
TurbosDex = { local = "../externals/turbos-dex", override = true }
BluefinSpot = { git = "https://github.com/fireflyprotocol/bluefin-spot-contract-interface.git", subdir = "", rev = "main", override = true }

[addresses]
cetus_aggregator_simple = "0x3239061b389dcc35be021bb13d174da82fafcc87bf3d8e176e6c62619311a90c"
